export const mockUser = {
  username: "arnavryie",
  displayName: "Arnav Tagade",
  avatar: "https://github.com/arnavryie.png",
  bio: "Full-stack engineer & CE student. Building AI tools and OSS projects.",
  location: "Pune, India",
  followers: 248,
  following: 45,
  skills: ["Python", "FastAPI", "React", "Next.js", "MongoDB"],
};

export const mockRepos = [
  {
    id: "1",
    owner: "hwchase17",
    name: "langchain",
    description: "Build context-aware reasoning applications with LangChain.",
    language: "Python",
    languageColor: "#3572A5",
    stars: 85400,
    forks: 13200,
    forkVelocity: 340,
    topics: ["llm", "orchestration", "ai", "python"],
    updatedAt: "2 hours ago",
    skillMatch: 3,
    trending: true,
  },
  {
    id: "2",
    owner: "vercel",
    name: "next.js",
    description: "The React Framework for the Web — built by Vercel.",
    language: "TypeScript",
    languageColor: "#3178c6",
    stars: 124000,
    forks: 26500,
    forkVelocity: 120,
    topics: ["react", "nextjs", "framework", "ssr"],
    updatedAt: "5 hours ago",
    skillMatch: 0,
    trending: false,
  },
  {
    id: "3",
    owner: "fastapi",
    name: "fastapi",
    description: "FastAPI framework, high performance, easy to learn, fast to code.",
    language: "Python",
    languageColor: "#3572A5",
    stars: 74200,
    forks: 6300,
    forkVelocity: 89,
    topics: ["python", "api", "rest", "async"],
    updatedAt: "1 day ago",
    skillMatch: 2,
    trending: false,
  },
  {
    id: "4",
    owner: "mongodb",
    name: "mongo-python-driver",
    description: "PyMongo - the official MongoDB driver for Python.",
    language: "Python",
    languageColor: "#3572A5",
    stars: 4100,
    forks: 1200,
    forkVelocity: 45,
    topics: ["mongodb", "python", "database", "driver"],
    updatedAt: "3 days ago",
    skillMatch: 2,
    trending: false,
  },
];

export const mockDevelopers = [
  {
    username: "gvanrossum",
    displayName: "Guido van Rossum",
    avatar: "https://avatars.githubusercontent.com/u/2894642",
    bio: "Python's creator. Currently at Microsoft.",
    location: "San Francisco, CA",
    repos: 42,
    followers: 9800,
    topLanguages: ["Python", "C"],
    recentActivity: "Pushed to python/cpython 2 hours ago",
    following: true,
  },
  {
    username: "tiangolo",
    displayName: "Sebastián Ramírez",
    avatar: "https://avatars.githubusercontent.com/u/1326112",
    bio: "Creator of FastAPI, Typer, SQLModel.",
    location: "Berlin, Germany",
    repos: 78,
    followers: 14200,
    topLanguages: ["Python", "TypeScript"],
    recentActivity: "Starred tiangolo/fastapi yesterday",
    following: true,
  },
  {
    username: "yannisgu",
    displayName: "Yannis G",
    avatar: "https://avatars.githubusercontent.com/u/9919",
    bio: "Open source enthusiast. Building dev tools.",
    location: "London, UK",
    repos: 34,
    followers: 3200,
    topLanguages: ["Go", "Rust"],
    recentActivity: "Merged PR in yannis/devtools 3 days ago",
    following: false,
  },
];

export const mockCommunities = [
  {
    slug: "ai-ml",
    name: "AI & Machine Learning",
    icon: "🤖",
    description: "Repositories, tools, and discussions around AI, ML, and LLMs.",
    members: 12400,
    repos: 340,
    color: "#58a6ff",
  },
  {
    slug: "ui-frontend",
    name: "UI & Frontend",
    icon: "⚛️",
    description: "React, Vue, Svelte, CSS frameworks, and UI component libraries.",
    members: 8900,
    repos: 220,
    color: "#8957e5",
  },
  {
    slug: "devops-infra",
    name: "DevOps & Infrastructure",
    icon: "⚙️",
    description: "Docker, Kubernetes, CI/CD pipelines, and cloud-native tools.",
    members: 6700,
    repos: 180,
    color: "#238636",
  },
  {
    slug: "databases",
    name: "Databases",
    icon: "🗄️",
    description: "SQL, NoSQL, vector databases, ORMs, and query engines.",
    members: 5400,
    repos: 140,
    color: "#d76027",
  },
];

export const mockIssues = [
  {
    id: 142,
    title: "Race condition in node scheduler when handling high-frequency data",
    labels: ["bug", "core-engine"],
    skillMatch: 92,
    impactScore: 88,
    impactLevel: "High",
    comments: 4,
    openedBy: "alex-ronin",
    openedAt: "2 hours ago",
  },
  {
    id: 140,
    title: "Implement gRPC streaming for log aggregation endpoint",
    labels: ["enhancement"],
    skillMatch: 78,
    impactScore: 62,
    impactLevel: "Med",
    comments: 1,
    openedBy: "sarah-dev",
    openedAt: "yesterday",
  },
  {
    id: 138,
    title: "Documentation: Update architectural diagrams for v2 engine",
    labels: ["docs", "good first issue"],
    skillMatch: 0,
    impactScore: 24,
    impactLevel: "Low",
    comments: 0,
    openedBy: "doc-bot",
    openedAt: "3 days ago",
  },
];

export const mockGraphNodes = [
  { id: "langchain", position: { x: 400, y: 200 }, data: { label: "langchain", stars: "85.4k" } },
  { id: "llamaindex", position: { x: 700, y: 100 }, data: { label: "llamaindex", stars: "34.2k" } },
  { id: "openai-sdk", position: { x: 700, y: 300 }, data: { label: "openai-sdk", stars: "22.1k" } },
  { id: "fastapi", position: { x: 150, y: 300 }, data: { label: "fastapi", stars: "74.2k" } },
  { id: "pydantic", position: { x: 150, y: 100 }, data: { label: "pydantic", stars: "19.8k" } },
];

export const mockGraphEdges = [
  { id: "e1", source: "langchain", target: "openai-sdk", label: "DEPENDS_ON", style: { stroke: "#58a6ff" } },
  { id: "e2", source: "langchain", target: "llamaindex", label: "COMPETES_WITH", style: { stroke: "#da3633" } },
  { id: "e3", source: "fastapi", target: "pydantic", label: "DEPENDS_ON", style: { stroke: "#58a6ff" } },
  { id: "e4", source: "langchain", target: "fastapi", label: "DEPENDS_ON", style: { stroke: "#58a6ff" } },
];
